# Generated by Django 2.1.1 on 2018-10-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_auto_20181005_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
